version: '3.7'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  app:
    build: ./app
    restart: always
    stdin_open: true
    tty: true

  client:
    build: ./client
